from Crypto.PublicKey import ECC

# Elliptic curve cipher (ECDSA)

def createPEM_ECDSA():
    key = ECC.generate(curve = 'P-256') # private key is generated by using the Elliptic curve cipher
    with open('privkey_ecdsa.pem', 'w') as h:
        h.write(key.export_key(format='PEM'))
    
    key = key.public_key()
    with open('pubkey_ecdsa.pem', 'w') as h:
        h.write(key.export_key(format='PEM'))

createPEM_ECDSA()