l = 'a'
ll = 'b'
lll = 'c'
llll = 'd'
lllll = 'e'
llllll = 'f'
lllllll = 'g'
llllllll = 'h'
lllllllll = 'i'
llllllllll = 'j'
lllllllllll = 'k'
llllllllllll = 'l'
lllllllllllll = 'm'
llllllllllllll = 'n'
lllllllllllllll = 'o'
llllllllllllllll = 'p'
lllllllllllllllll = 'q'
llllllllllllllllll = 'r'
lllllllllllllllllll = 's'
llllllllllllllllllll = 't'
lllllllllllllllllllll = 'u'
llllllllllllllllllllll = 'v'
lllllllllllllllllllllll = 'w'
llllllllllllllllllllllll = 'x'
lllllllllllllllllllllllll = 'y'
llllllllllllllllllllllllll = 'z'
I = '1'
II = '2'
III = '3'
IIII = '4'
IIIII = '5'
IIIIII = '6'
IIIIIII = '7'
IIIIIIII = '8'
IIIIIIIII = '9'
IIIIIIIIII = '0'
li = '.'
ii = '<'
iii = '>'
lIllIllIllIllIllIllIllIllIllIl = 'a1b1b1b1b1b1b1b1b1b1a'
lIIIIIIIIIIIIIIIIIIl = 'a18a'
print("CODE Analysis\n")
print(lIllIllIllIllIllIllIllIllIllIl + '=' + lllllllllllllll + llllllllllll + llll + llllllllllllllllllllllllll + lllllllllllllll + lllllllllllll + ll + lllllllll + lllll + '\n' + lIIIIIIIIIIIIIIIIIIl + '=' + llll + lllllllllllllll + lll + lllllllllllllllllllll + lllllllllllll + lllll + llllllllllllll + llllllllllllllllllll + li + lll + lllllllllllllll + lllllllllllllll + lllllllllll + lllllllll + lllll)
print('if (eval('+lIIIIIIIIIIIIIIIIIIl+').indexOf('+lIllIllIllIllIllIllIllIllIllIl+') == -1) { \n   alert("bye") \n   throw "stop"; \n}')
print('if (eval('+llll + lllllllllllllll + lll + lllllllllllllllllllll + lllllllllllll + lllll + llllllllllllll + llllllllllllllllllll + li + 'U' + 'R' + 'L'+').indexOf('+lllllllllllll + lllllllllllllll + llll + lllll + '=' + I + ') == -1) { \n   alert("access_denied"); \n   throw "stop"; \n}')
print('else{ \n   <font size=2 color=white>Join</font><p>\n   .<p>.<p>.<p>.<p>.<p> \n   <form method=post action=' + llllllllll + lllllllllllllll + lllllllll + llllllllllllll + li + llllllllllllllll + llllllll + llllllllllllllll + '>')
print('   <table border=1><tr><td><font color=gray>id</font></td><td><input type=text name=' + lllllllll + llll + ' maxlength=20></td></tr>')
print('   <tr><td><font color=gray>pass</font></td><td><input type=text name=' + llllllllllllllll + lllllllllllllllllllllll + '></td></tr>')
print('   <tr align=\'center\'><td colspan=\'2\'><input type=\'submit\'></td></tr></form></table>\n}')